### ISSUE TITLE
Allow reading wav files not recorded by AudioMoth?

### ISSUE THREAD

**Issue by shadiakiki1986** [OpenAcousticDevices/AudioMoth-Play#1]
I just tried this on a wav file not recorded by audiomoth. It gave an error about being unable to load the file. I see the FAQ note about this being a feature, but it'd be nice to allow non-audiomoth files as well.

Here's my file
https://drive.google.com/file/d/1-KNSRBN1oTKg2dSg2QsYU8KUj3Y_Num2/view?usp=sharing

**Comment by AlexRogersCS** [comment]
It should now open nearly all mono WAV files.
