### ISSUE TITLE
WAV: File format is not supported

### ISSUE THREAD

**Issue by satelllte** [OpenAcousticDevices/AudioMoth-Play#2]
## About the issue

Hi 👋 
At https://play.openacousticdevices.info, I'm trying to load a WAV file by clicking "Select File" and choosing it on my computer. It says:

```
File format is not supported.
  readFromFile @ index.js:2847
  await in readFromFile (async)
  loadFile @ index.js:3098
  await in loadFile (async)
  (anonymous) @ index.js:3340
```

## Environment

Browser: Google Chrome 116
OS: Mac OS 13.4.1

**Comment by mattdesl** [comment]
I had the same issue, it might just be that the file is stereo instead of mono.
